import type { Metadata } from "next";
import { Geist, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "../components/common/header";
import { Providers } from "./providers";
import Sheet from "../components/ui/sheet/sheet";
import GlobalOverlays from "../components/ui/GlobalOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-main",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Schedule",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} ${jakarta.variable} antialiased`}
    >
      <body className="bg-main-bg w-full h-screen flex justify-center">
        <div className="flex max-w-[1400px] w-full flex-col h-full px-16 py-8">
          <Header />

          <div className="realtive flex flex-1 gap-8 pt-4 overflow-hidden">
            <main className="flex-1">
              <Providers>{children}</Providers>
              <GlobalOverlays />
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
